# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viapublica_app', '0004_reclamo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='image',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/reclamos/'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
